import argparse
import itertools
from collections.abc import Callable

import numpy as np

from examples import ArionScene
from lib import audio
from lib.arion_lights import LightConfig, Panel
from lib.scenes import FrameContext, Overlay, SceneConfig
from lib.virtualrig import VirtualRig

group1names = ["g", "h", "i", "t", "u", "v"]
group2names = ["e", "f", "q", "r", "s"]
group3names = ["a", "b", "c", "d", "m", "n", "o", "p"]
groupnames = [group1names, group2names, group3names]


class Group:
    def __init__(
        self,
        freq_range: tuple[float, float],
        panels: Callable[[LightConfig], list[Panel]],
        scale: float = 1,
    ):
        self.freq_range = freq_range
        self.scale = scale
        self.panel_names = panels


class VisualiserDimmerOverlay(Overlay):
    def __init__(self):
        super().__init__()
        self.groups = [
            Group((1, 130), group1names, 1),
            Group((130, 300), group2names, 1.5),
            Group((300, 5000), group3names, 2.5),
        ]

        self.scaling = 5
        self.max_value_clamp = 1.5

        # below values initialised in apply to ensure audio devce information is present
        self.blocksize = None
        self.samplingrate = None
        self.frequcey_values = None
        self.range_indicies = None
        self.visuliser_values = None
        self.fft_values = None

    def smoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
        return 0.90 * old + 0.10 * new

    def maxsmoothing(self, old: np.ndarray, new: np.ndarray) -> np.ndarray:
        return np.minimum(np.maximum(old, new) * 0.90, self.max_value_clamp)

    def apply(self, context: FrameContext) -> LightConfig:
        lights = context.lights
        audio_data = context.audio_data

        if audio_data is None:
            raise RuntimeError(
                "No audio data availabe. Do you have the correct scene type?"
            )

        if self.frequcey_values is None:
            self.blocksize = audio.blocksize
            self.samplingrate = audio.samplingrate

            # frequencey buckets generated by fft
            self.frequcey_values = np.fft.rfftfreq(
                self.blocksize, d=1 / self.samplingrate
            )
            # indicies corresponding to frequencey ranges
            self.range_indicies: list[tuple[int, int]] = [
                (
                    np.searchsorted(self.frequcey_values, group.freq_range[0]),
                    np.searchsorted(self.frequcey_values, group.freq_range[1]),
                )
                for group in self.groups
            ]

            self.visuliser_values = np.zeros(len(self.groups))        
            self.fft_values = np.zeros(len(self.frequcey_values))

        # performs fourier transform resulting buckets are frequencey_values
        self.fft_values = np.abs(np.fft.rfft(audio_data))
        self.fft_values *= self.scaling / len(audio_data)  # normalise

        newvalues = np.array(
            [np.max(self.fft_values[start:end]) for start, end in self.range_indicies]
        )

        self.visuliser_values = self.maxsmoothing(self.visuliser_values, newvalues)

        for i, grp in enumerate(self.groups):
            scale = 0.3 + 0.7 * grp.scale * self.visuliser_values[i]
            if i != 0:  # side chain prevents kick overpowering
                scale -= 0.25 * self.visuliser_values[0]
            for panelname in grp.panel_names:
                panel = getattr(lights.panels, panelname, None)
                panel.r *= scale
                panel.g *= scale
                panel.b *= scale

        return context


# if you run this file directly you get an example
if __name__ == "__main__":
    # controller = ArtNetController("192.168.1.169")

    from lib import audio

    audio.select_device(auto=True)

    scene = ArionScene(SceneConfig.mic(), [VisualiserDimmerOverlay()])
    scene.start()
    rig = VirtualRig()
    scene.start_dispatcher(rig.callback)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-g",
        "--graph",
        action="store_true",
        help="enables matplotlib graph display of visuliser bins",
    )
    args = parser.parse_args()

    # ==============================
    # PLOTTING STUFF
    # ==============================
    if args.graph:
        import matplotlib.pyplot as plt
        from matplotlib import animation

        overlay = scene.overlays[0]

        def live_plot():
            # Set up the figure and axis
            fig, ax = plt.subplots(figsize=(10, 5))

            # 1. Plot the 257 FFT buckets against the frequency values
            (line,) = ax.plot(
                overlay.frequcey_values,
                np.zeros_like(overlay.frequcey_values),
                color="b",
                alpha=0.6,
                label="FFT Spectrum (Scaled)",
            )

            bound_frequencies = overlay.frequcey_values[
                list(itertools.chain(*(overlay.range_indicies)))
            ]
            for bound in bound_frequencies:
                ax.axvline(
                    x=bound,
                    color="gray",
                    linestyle="--",
                    alpha=0.7,
                    label="Group Bound" if bound == bound_frequencies[0] else "",
                )

            # 3. Calculate the center frequency (arithmetic middle) of each group for the dots
            middle_frequencies = [
                (overlay.frequcey_values[start] + overlay.frequcey_values[end - 1]) / 2
                for start, end in overlay.range_indicies
            ]

            # Initialize the scatter dots representing the calculated value for each group
            dots = ax.scatter(
                middle_frequencies,
                np.zeros(len(groupnames)),
                color="red",
                s=60,
                zorder=5,
                label="Group Average (Smoothed)",
            )

            # Aesthetics and limits
            ax.set_xlabel("Frequency (Hz)")
            ax.set_ylabel("Amplitude")
            ax.set_title("Live Audio FFT Spectrum & Frequency Groups")
            # Focus view on your active range up to 16kHz
            ax.set_xlim(min(bound_frequencies) * 0.95, max(bound_frequencies) * 1.05)
            ax.set_xscale("log")
            ax.set_ylim(0, 2)  # Initial y-limit
            ax.set_autoscaley_on(False)
            ax.legend(loc="upper right")
            ax.grid(True, alpha=0.3)

            # Animation update loop called periodically by FuncAnimation
            def update(frame):
                # Update the main FFT line data
                line.set_ydata(overlay.fft_values)

                # Update the y-coordinates of the 4 group dots
                dots.set_offsets(
                    np.column_stack((middle_frequencies, overlay.visuliser_values))
                )

                return line, dots

            # Create the animation loop (interval=30ms targets ~33 FPS)
            ani = animation.FuncAnimation(  # noqa:F841
                fig, update, interval=30, blit=False, cache_frame_data=False
            )

            # Keeps the window open and processing events until closed manually
            plt.show()

        live_plot()

    rig.run()

    input("Press enter to close")
