import threading

import lib.arion_lights as light
import lib.artnetcontroller as anc

import itertools

import sounddevice as sd

import numpy as np

import matplotlib.pyplot as plt
import matplotlib.animation as animation


controller = anc.ArtNetController("192.168.1.169")


class Group:
    def __init__(self, freq_range: tuple[float, float], panels: list[light.Panel], scale: float = 1, r: int = 0, g: int = 0, b: int = 0):
        self.freq_range = freq_range
        self.scale = scale
        self.panels = panels
        self.r = r
        self.g = g
        self.b = b


# panels: m is not connected
groups = [Group((1, 130), [light.panels.d, light.panels.h, light.panels.n, light.panels.m, light.panels.t, light.panels.v], 1, 0, 255, 0),
          Group((130, 300), [light.panels.b, light.panels.e, light.panels.g, light.panels.f,
                light.panels.r, light.panels.s], 1.5, 255, 255, 255),
          Group((300, 5000), [light.panels.a, light.panels.c, light.panels.i, light.panels.o, light.panels.p, light.panels.q, light.panels.u], 2.5, 0, 0, 255)]


inputdev = sd.query_devices(kind="input")
inputdevind = inputdev['index']
print(f"Using input device: {inputdev["name"]}")

channels = inputdev['max_input_channels']

if channels == 0:
    raise ValueError("Max possible channel count 0 :(")


samplingrate = inputdev['default_samplerate']
blocksize = 1024
print(f"Update rate = samplingrate / blocksize = {samplingrate / blocksize}")
# frequencey buckets generated by fft
frequcey_values = np.fft.rfftfreq(blocksize, d=1/samplingrate)
# indicies corresponding to frequencey ranges
range_indicies: list[tuple[int, int]] = [(
    np.searchsorted(frequcey_values, group.freq_range[0]),
    np.searchsorted(frequcey_values, group.freq_range[1]))
    for group in groups
]

scaling = 5
max_value_clamp = 1.5


visuliser_values = np.zeros(len(groups))
fft_values = np.zeros(len(frequcey_values))


def smoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
    return 0.90 * old + 0.10 * new


def maxsmoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
    return np.minimum(np.maximum(old, new) * 0.95, max_value_clamp)


def process_audio_data(indata: np.ndarray) -> None:
    """Perfoms fft proccesing on data and updates visuliser_values and fft_values globals"""
    global visuliser_values, fft_values

    channel_1 = indata[:, 0]
    # performs fourier transform resulting buckets are frequencey_values
    fft_values = np.abs(np.fft.rfft(channel_1))
    fft_values *= scaling / len(channel_1)  # normalise

    newvalues = np.array([np.max(fft_values[start:end])
                          for start, end in range_indicies])

    visuliser_values = maxsmoothing(visuliser_values, newvalues)


def live_plot():
    # Set up the figure and axis
    fig, ax = plt.subplots(figsize=(10, 5))

    # 1. Plot the 257 FFT buckets against the frequency values
    line, = ax.plot(frequcey_values, np.zeros_like(frequcey_values),
                    color='b', alpha=0.6, label='FFT Spectrum (Scaled)')

    bound_frequencies = frequcey_values[list(itertools.chain(*range_indicies))]
    print(bound_frequencies)
    for bound in bound_frequencies:
        ax.axvline(x=bound, color='gray', linestyle='--', alpha=0.7,
                   label='Group Bound' if bound == bound_frequencies[0] else "")

    # 3. Calculate the center frequency (arithmetic middle) of each group for the dots
    middle_frequencies = [
        (frequcey_values[start] + frequcey_values[end - 1]) / 2
        for start, end in range_indicies
    ]

    # Initialize the scatter dots representing the calculated value for each group
    dots = ax.scatter(middle_frequencies, np.zeros(
        len(groups)), color='red', s=60, zorder=5, label='Group Average (Smoothed)')

    # Aesthetics and limits
    ax.set_xlabel('Frequency (Hz)')
    ax.set_ylabel('Amplitude')
    ax.set_title('Live Audio FFT Spectrum & Frequency Groups')
    # Focus view on your active range up to 16kHz
    ax.set_xlim(min(bound_frequencies) * 0.95, max(bound_frequencies) * 1.05)
    ax.set_xscale('log')
    ax.set_ylim(0, 2)  # Initial y-limit
    ax.set_autoscaley_on(False)
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    # Animation update loop called periodically by FuncAnimation
    def update(frame):
        # Update the main FFT line data
        line.set_ydata(fft_values)

        # Update the y-coordinates of the 4 group dots
        dots.set_offsets(np.column_stack(
            (middle_frequencies, visuliser_values)))

        return line, dots

    # Create the animation loop (interval=30ms targets ~33 FPS)
    ani = animation.FuncAnimation(
        fig, update, interval=30, blit=False, cache_frame_data=False)

    # Keeps the window open and processing events until closed manually
    plt.show()


def main_loop():
    # background lighting
    for head in light.overheads:
        head.setLight(255, 255, 255, 30)

    stream = sd.InputStream(device=inputdevind,
                            blocksize=blocksize, channels=channels)
    stream.start()
    while True:
        # process audio data
        # is blocking will wait for whole block
        # set blocksize to match dmx update rate (44 hz)
        data, overflowed = stream.read(blocksize)
        if overflowed:
            print("Datastream overflowed, calculations taking too long")

        process_audio_data(data)

        for i, grp in enumerate(groups):
            scale = 0.3 + 0.7 * grp.scale * visuliser_values[i]
            if i != 0:  # side chain prevents kick overpowering
                scale -= 0.25 * visuliser_values[0]
            for panel in grp.panels:
                panel.setLight(grp.r * scale, grp.g *
                               scale, grp.b * scale)

        controller.send_packet(light.get_channel_values())


# have main loop on a seperate thread because matplotlib requires main thread
main = threading.Thread(target=main_loop, daemon=True)

main.start()

live_plot()
