import argparse
import itertools
from collections.abc import Callable

import numpy as np

from lib import audio
from lib.arion_lights import LightConfig, Panel
from lib.scenes import AudioOverlay, AudioScene, SceneScript

audio.select_device()

class Group:
    def __init__(self, freq_range: tuple[float, float], panels: Callable[[LightConfig], list[Panel]], scale: float = 1, r: float = 1, g: float = 1, b: float = 1):
        self.freq_range = freq_range
        self.scale = scale
        self.panels = panels
        self.r = r
        self.g = g
        self.b = b

# panels: m is not connected i think
# The groups are only defined outside the classes here as the background and the overlay need the same groupings.
# This is pretty unclean tbh but works for now 
def getgroup1(lights: LightConfig) -> list[Panel]:
    return [lights.panels.d, lights.panels.h, lights.panels.n, lights.panels.m, lights.panels.t, lights.panels.v]

def getgroup2(lights: LightConfig) -> list[Panel]:
    return [lights.panels.b, lights.panels.e, lights.panels.g, lights.panels.f, lights.panels.r, lights.panels.s]

def getgroup3(lights: LightConfig) -> list[Panel]:
    return [lights.panels.a, lights.panels.c, lights.panels.i, lights.panels.o, lights.panels.p, lights.panels.q, lights.panels.u]

groups = [Group((1, 130), getgroup1, 1, 0, 255, 0), # arion colors
          Group((130, 300), getgroup2, 1.5, 255, 255, 255),
          Group((300, 5000), getgroup3, 2.5, 0, 0, 255)]
class VisualiserBackground(SceneScript):
    def run(self):
        lights = self.lights
        for group in groups:
            for panel in group.panels(lights):
                panel.setLight(group.r, group.g, group.b)

class VisualiserDimmerOverlay(AudioOverlay):
    def __init__(self):
        if audio.inputdevind is None:
            raise RuntimeError("No audio input device found. Please confirm the audio library has a called select_device before initialising this class")

        self.blocksize = audio.blocksize
        self.samplingrate = audio.samplingrate

        # frequencey buckets generated by fft
        self.frequcey_values = np.fft.rfftfreq(self.blocksize, d=1/self.samplingrate)
        # indicies corresponding to frequencey ranges
        self.range_indicies: list[tuple[int, int]] = [(
            np.searchsorted(self.frequcey_values, group.freq_range[0]),
            np.searchsorted(self.frequcey_values, group.freq_range[1]))
            for group in groups
        ]

        self.scaling = 5
        self.max_value_clamp = 1.5

        # these are globals so that both plotting and auio processing threads can access them
        self.visuliser_values = np.zeros(len(groups))
        self.fft_values = np.zeros(len(self.frequcey_values))


    def smoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
        return 0.90 * old + 0.10 * new

    def maxsmoothing(self, old: np.ndarray, new: np.ndarray) -> np.ndarray:
        return np.minimum(np.maximum(old, new) * 0.90, self.max_value_clamp)

    def apply(self, lights, audio_data: np.ndarray) -> LightConfig:
        # performs fourier transform resulting buckets are frequencey_values
        self.fft_values = np.abs(np.fft.rfft(audio_data))
        self.fft_values *= self.scaling / len(audio_data)  # normalise
    
        newvalues = np.array([np.max(self.fft_values[start:end])
                                for start, end in self.range_indicies])
    
        self.visuliser_values = self.maxsmoothing(self.visuliser_values, newvalues)

        for i, grp in enumerate(groups):
            scale = 0.3 + 0.7 * grp.scale * self.visuliser_values[i]
            if i != 0:  # side chain prevents kick overpowering
                scale -= 0.25 * self.visuliser_values[0]
            for panel in grp.panels(lights):
                panel.r *= scale
                panel.g *= scale
                panel.b *= scale


scene = AudioScene(VisualiserBackground(), [VisualiserDimmerOverlay()], lambda lights: None)
scene.start()

parser = argparse.ArgumentParser()
parser.add_argument('-g', '--graph',
                    action='store_true', help="enables matplotlib graph display of visuliser bins")
args = parser.parse_args()

# ==============================
# PLOTTING STUFF
# ==============================
if args.graph:
    import matplotlib.pyplot as plt
    from matplotlib import animation

    overlay = scene.overlays[0]

    def live_plot():
        # Set up the figure and axis
        fig, ax = plt.subplots(figsize=(10, 5))

        # 1. Plot the 257 FFT buckets against the frequency values
        line, = ax.plot(overlay.frequcey_values, np.zeros_like(overlay.frequcey_values),
                        color='b', alpha=0.6, label='FFT Spectrum (Scaled)')

        bound_frequencies = overlay.frequcey_values[list(
            itertools.chain(*(overlay.range_indicies)))]
        for bound in bound_frequencies:
            ax.axvline(x=bound, color='gray', linestyle='--', alpha=0.7,
                       label='Group Bound' if bound == bound_frequencies[0] else "")

        # 3. Calculate the center frequency (arithmetic middle) of each group for the dots
        middle_frequencies = [
            (overlay.frequcey_values[start] + overlay.frequcey_values[end - 1]) / 2
            for start, end in overlay.range_indicies
        ]

        # Initialize the scatter dots representing the calculated value for each group
        dots = ax.scatter(middle_frequencies, np.zeros(
            len(groups)), color='red', s=60, zorder=5, label='Group Average (Smoothed)')

        # Aesthetics and limits
        ax.set_xlabel('Frequency (Hz)')
        ax.set_ylabel('Amplitude')
        ax.set_title('Live Audio FFT Spectrum & Frequency Groups')
        # Focus view on your active range up to 16kHz
        ax.set_xlim(min(bound_frequencies) * 0.95,
                    max(bound_frequencies) * 1.05)
        ax.set_xscale('log')
        ax.set_ylim(0, 2)  # Initial y-limit
        ax.set_autoscaley_on(False)
        ax.legend(loc='upper right')
        ax.grid(True, alpha=0.3)

        # Animation update loop called periodically by FuncAnimation
        def update(frame):
            # Update the main FFT line data
            line.set_ydata(overlay.fft_values)

            # Update the y-coordinates of the 4 group dots
            dots.set_offsets(np.column_stack(
                (middle_frequencies, overlay.visuliser_values)))

            return line, dots

        # Create the animation loop (interval=30ms targets ~33 FPS)
        ani = animation.FuncAnimation(  # noqa:F841
            fig, update, interval=30, blit=False, cache_frame_data=False)

        # Keeps the window open and processing events until closed manually
        plt.show()

    live_plot()

input("Press enter to close")