import time

import lib.arion_lights as light
import lib.artnetcontroller as anc

import itertools
import sys

import sounddevice as sd

import numpy as np

import matplotlib.pyplot as plt
import matplotlib.animation as animation


inputdev = sd.query_devices(kind="input")
inputdevind = inputdev['index']
print(inputdev)

channels = inputdev['max_input_channels']

if channels == 0:
    raise ValueError("Max possible channel count 0 :(")


samplingrate = inputdev['default_samplerate']
blocksize = 512
# frequencey buckets generated by fft
frequcey_values = np.fft.rfftfreq(blocksize, d=1/samplingrate)
print(frequcey_values)
# indicies corresponding to frequencey ranges
range_boundaries = [1, 130, 300, 5000, 10000]
range_indicies = np.searchsorted(frequcey_values, range_boundaries)

scaling = 5
max_value_clamp = 1.5


visuliser_values = np.zeros(len(range_boundaries) - 1)
fft_values = np.zeros(len(frequcey_values))


def smoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
    return 0.90 * old + 0.10 * new


def maxsmoothing(old: np.ndarray, new: np.ndarray) -> np.ndarray:
    return np.minimum(np.maximum(old, new) * 0.95, max_value_clamp)


def callback(indata: np.ndarray, frames: int,
             time, status) -> None:
    global visuliser_values, fft_values
    if status:
        print(status, file=sys.stderr)

    channel_1 = indata[:, 0]
    # performs fourier transform resulting buckets are frequencey_values
    fft_values = np.abs(np.fft.rfft(channel_1))
    fft_values *= scaling / len(channel_1)  # normalise

    newvalues = np.array([np.max(fft_values[start:end])
                          for start, end in itertools.pairwise(range_indicies)])

    visuliser_values = maxsmoothing(visuliser_values, newvalues)


def live_plot():
    # Set up the figure and axis
    fig, ax = plt.subplots(figsize=(10, 5))

    # 1. Plot the 257 FFT buckets against the frequency values
    line, = ax.plot(frequcey_values, np.zeros_like(frequcey_values),
                    color='b', alpha=0.6, label='FFT Spectrum (Scaled)')

    bound_frequencies = frequcey_values[range_indicies]
    for bound in bound_frequencies:
        ax.axvline(x=bound, color='gray', linestyle='--', alpha=0.7,
                   label='Group Bound' if bound == bound_frequencies[0] else "")

    # 3. Calculate the center frequency (arithmetic middle) of each group for the dots
    middle_frequencies = [
        (frequcey_values[start] + frequcey_values[end - 1]) / 2
        for start, end in itertools.pairwise(range_indicies)
    ]

    # Initialize the scatter dots representing the calculated value for each group
    dots = ax.scatter(middle_frequencies, np.zeros(
        len(range_boundaries) - 1), color='red', s=60, zorder=5, label='Group Average (Smoothed)')

    # Aesthetics and limits
    ax.set_xlabel('Frequency (Hz)')
    ax.set_ylabel('Amplitude')
    ax.set_title('Live Audio FFT Spectrum & Frequency Groups')
    # Focus view on your active range up to 16kHz
    ax.set_xlim(min(bound_frequencies) * 0.95, max(bound_frequencies) * 1.05)
    ax.set_xscale('log')
    ax.set_ylim(0, 2)  # Initial y-limit
    ax.set_autoscaley_on(False)
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    # Animation update loop called periodically by FuncAnimation
    def update(frame):
        # Update the main FFT line data
        line.set_ydata(fft_values)

        # Update the y-coordinates of the 4 group dots
        dots.set_offsets(np.column_stack(
            (middle_frequencies, visuliser_values)))

        return line, dots

    # Create the animation loop (interval=30ms targets ~33 FPS)
    ani = animation.FuncAnimation(
        fig, update, interval=30, blit=False, cache_frame_data=False)

    # Keeps the window open and processing events until closed manually
    plt.show()


stream = sd.InputStream(device=inputdevind,
                        blocksize=blocksize, channels=channels, callback=callback)

stream.start()
live_plot()


controller = anc.ArtNetController("192.168.1.169")


class Group:
    def __init__(self, range_idx: int, panels: list[light.Panel], scale: float = 1, r: int = 0, g: int = 0, b: int = 0):
        self.range_idx: int = range_idx
        self.scale: float = scale
        self.panels: list[light.Panel] = panels
        self.r: int = r
        self.g: int = g
        self.b: int = b


# panels: m is not connected
groups = [Group(0, [light.panels.d, light.panels.h, light.panels.n, light.panels.m, light.panels.t, light.panels.v], 1, 0, 255, 0),
          Group(1, [light.panels.b, light.panels.e, light.panels.g, light.panels.f,
                light.panels.r, light.panels.s], 1.5, 255, 255, 255),
          Group(2, [light.panels.a, light.panels.c, light.panels.i, light.panels.o, light.panels.p, light.panels.q, light.panels.u], 2.5, 0, 0, 255)]

for head in light.overheads:
    head.setLight(255, 255, 255, 30)

while True:
    for grp in groups:
        scale = 0.3 + 0.7 * grp.scale * visuliser_values[grp.range_idx]
        if grp != groups[0]:
            scale -= 0.5 * visuliser_values[0]
        for panel in grp.panels:
            panel.setLight(grp.r * scale, grp.g *
                           scale, grp.b * scale)

    controller.send_packet(light.get_channel_values())

    time.sleep(0.025)
